version: "3"
services:
  front:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "yarn start"
    ports:
      - "3000:3000"